kefis/lib/kefis_web/router.ex
defmodule KefisWeb.Router do
  use KefisWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {KefisWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug KefisWeb.ApiAuth, otp_app: :kefis
  end

  pipeline :api_protected do
    plug Pow.Plug.RequireAuthenticated, error_handler: KefisWeb.ApiAuthErrorHandler
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: KefisWeb.AuthErrorHandler
  end

  pipeline :not_authenticated do
    plug Pow.Plug.RequireNotAuthenticated,
      error_handler: KefisWeb.AuthErrorHandler
  end

  scope "/" do
    pipe_through [:browser, :not_authenticated]

    pow_routes()
  end

  scope "/", KefisWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/", KefisWeb do
    pipe_through [:browser, :protected]
    resources "/users", UserController
    resources "/products", ProductController
    # resources "/partners", PartnerController

    get "/partners/user/new", PartnerController, :new_partner_user
    post "/partners/user/new", PartnerController, :create_partner_user
    get "/partners/user/:id", PartnerController, :show_partner_user
  end

  scope "/", KefisWeb do
    pipe_through [:browser, :not_authenticated]

    # get "/signup", RegistrationController, :new, as: :signup
    # post "/signup", RegistrationController, :create, as: :signup
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
  end

  scope "/", KefisWeb do
    pipe_through [:browser, :protected]

    delete "/logout", SessionController, :delete, as: :logout
  end

  scope "/admin", KefisWeb do
    pipe_through [:browser, :protected]

    live "/", Admin.IndexLive

    live "/warehouses", Admin.Warehouse.IndexLive, :list
    live "/warehouses/new", Admin.Warehouse.IndexLive, :new
    live "/warehouses/:id", Admin.Warehouse.IndexLive, :update

    live "/transactions", Admin.Transaction.IndexLive, :transaction_index
    live "/transactions/:id", Admin.Transaction.IndexLive, :transaction_detail

    live "/partners/new", Admin.Partner.NewLive
    live "/partners/retailer", Admin.Partner.IndexLive, :retailer
    live "/partners/supplier", Admin.Partner.IndexLive, :supplier

    live "/partners/:id", Admin.Partner.IndexLive, :partner_details
    live "/partners/:id/edit", Admin.Partner.IndexLive, :edit_partner
    live "/partners/:id/orders", Admin.Partner.IndexLive, :partner_order
    live "/partners/:id/orders/:id", Admin.Partner.IndexLive, :partner_order_details

    live "/partners/:id/products/", Admin.Partner.Product.IndexLive, :partner_products
    live "/partners/:id/products/new", Admin.Partner.Product.IndexLive, :new_partner_product
    live "/partners/:id/products/:product", Admin.Partner.Product.IndexLive, :show_partner_product

    live "/partners/:id/products/:product/edit",
         Admin.Partner.Product.IndexLive,
         :edit_partner_product

    live "/partners/:id/transactions", Admin.Partner.IndexLive, :partner_transactions

    live "/orders", Admin.Order.IndexLive, :index
    live "/orders/:id", Admin.Order.IndexLive, :detail
    live "/orders/:id/info", Admin.Order.IndexLive, :info

    live "/map", Admin.Partner.IndexLive, :partner_map

    live "/users", Admin.User.IndexLive
  end

  scope "/partners", KefisWeb do
    pipe_through [:browser, :protected]

    get "/", PartnerController, :index
    get "/products", PartnerController, :list_partner_products

    get "/products/new", PartnerController, :new_product
    post "/products/new", PartnerController, :create_product

    get "/partners/products/:id", PartnerController, :show_product
    get "/partners/products/:id/edit", PartnerController, :edit_product
    delete "/partners/products/:id/delete", PartnerController, :delete_product
  end

  scope "/drivers", KefisWeb do
    pipe_through [:browser, :protected, :driver]

    live "/", Driver.DashboardLive, :index
    live "/trips", Driver.TripsLive
    live "/trips/collection", Driver.TripsLive, :collections
    live "/trips/delivery", Driver.TripsLive, :delivery

    live "/order", Driver.OrderLive
  end

  scope "/r", KefisWeb do
    pipe_through [:browser, :protected, :retailer]
    # pipe_through [:browser]

    live "/", Retailer.IndexLive

    live "/order", Retailer.OrdersLive, :index
    live "/order/new", Retailer.NewLive
    live "/order/history", Retailer.OrdersLive, :history
    live "/order/:id", Retailer.OrdersLive, :show_order

    live "/transactions", Retailer.OrdersLive, :list_my_transaction
    live "/transactions/transact", Retailer.OrdersLive, :transact
    live "/transactions/:id", Retailer.OrdersLive, :show_my_transaction

    # get "/order/new", RetailerController, :order
    live "/order/info", Retailer.ConfirmOrderLive
  end

  scope "/pos", KefisWeb do
    pipe_through [:browser, :protected, :retailer]
    # pipe_through [:browser]
  end

  scope "/s", KefisWeb do
    pipe_through [:browser, :protected, :supplier]
    # pipe_through [:browser]

    # get "/", SupplierController, :index
    # get "/products", SupplierController, :list_partner_products

    # get "/new/product", SupplierController, :new_product

    live "/", Supplier.IndexLive, :supplier_home
    live "/products", Supplier.Product.IndexLive, :list_product
    live "/products/new", Supplier.Product.IndexLive, :new_product
    live "/products/:id", Supplier.Product.IndexLive, :show_product
    live "/products/:id/edit", Supplier.Product.IndexLive, :edit_product

    live "/transactions/transact", Supplier.IndexLive, :transact_supplier
    live "/transactions", Supplier.IndexLive, :list_transactions
    live "/transactions/:id", Supplier.IndexLive, :show_transaction

    live "/orders", Supplier.IndexLive, :list_my_orders
    live "/orders/:id", Supplier.IndexLive, :show_my_orders

    # get "/orders", SupplierController, :my_orders
    # get "/orders/:id/", SupplierController, :show_order_details
  end

  scope "/w", KefisWeb do
    # pipe_through [:browser, :protected, :warehouse]
    pipe_through [:browser]

    live "/", Warehouse.IndexLive
    live "/incoming", Warehouse.OrdersLive, :incoming
    live "/processing", Warehouse.OrdersLive, :processing
    live "/outgoing", Warehouse.OrdersLive, :outgoing
    live "/info", Warehouse.ShowDetailLive
  end

  # Other scopes may use custom stacks.
  scope "/api", KefisWeb do
    pipe_through :api

    post "/login", SessionController, :api_create, as: :api_login

    # delete "/logout", SessionController, :api_delete, as: :api_logout
    post "/session/renew", SessionController, :renew
  end

  scope "/api/admin", KefisWeb do
    # pipe_through [:api, :api_protected, :api_admin]
    pipe_through :api

    get "/partners", AdminController, :api_list_partners
    post "/partners/new", AdminController, :api_add_partner
    get "/partners/:id", AdminController, :api_admin_show_partner
    post "/partners/:id/edit", AdminController, :api_update_partner
    delete "/partners/:id", AdminController, :api_delete_partner
    get "/partners/:id/products", AdminController, :api_show_partner_w_products

    get "/partners/:id/products/:id", AdminController, :api_show_partner_w_products
    post "/partners/:id/products/new", AdminController, :api_add_product
    post "/partners/:id/products/:product_id/edit", AdminController, :api_update_product
    delete "/partners/:id/products/:product_id/delete", AdminController, :api_delete_product

    get "/orders", AdminController, :api_list_orders
    get "/orders/:id", AdminController, :api_show_order
  end

  scope "/api/s", KefisWeb do
    pipe_through [:api, :api_supplier]

    get "/partners", AdminController, :api_list_partners
    get "/partners/:id", AdminController, :api_show_partner
  end

  scope "/api/r", KefisWeb do
    pipe_through [:api, :api_retailer]

    get "/partners", AdminController, :api_list_partners
    get "/partners/:id", AdminController, :api_show_partner
  end

  scope "/api", KefisWeb do
    pipe_through [:api, :api_protected]
    delete "/logout", SessionController, :delete, as: :logout
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: KefisWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

kefis/lib/kefis_web/controllers/partner_controller.ex
defmodule KefisWeb.PartnerController do
  use KefisWeb, :controller

  alias Kefis.Chain
  alias Kefis.Chain.Partner
  alias Kefis.Users.User
  alias Kefis.Partners
  alias Kefis.Products

  alias Kefis.Chain.Product

  alias Kefis.Products

  def index(conn, _params) do
    partners = Chain.list_partners()
    render(conn, "index.html", partners: partners)
  end

  def new(conn, _params) do
    changeset = Chain.change_partner(%Partner{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"partner" => partner_params}) do
    case Partners.create_partner(partner_params) do
      {:ok, partner} ->
        conn
        |> put_flash(:info, "Partner created successfully.")
        |> put_session(:partner, partner)
        |> redirect(to: Routes.partner_path(conn, :new_partner_user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    partner = Chain.get_partner!(id)
    render(conn, "show.html", partner: partner)
  end

  def edit(conn, %{"id" => id}) do
    partner = Chain.get_partner!(id)
    changeset = Chain.change_partner(partner)
    render(conn, "edit.html", partner: partner, changeset: changeset)
  end

  def update(conn, %{"id" => id, "partner" => partner_params}) do
    partner = Chain.get_partner!(id)

    case Chain.update_partner(partner, partner_params) do
      {:ok, partner} ->
        conn
        |> put_flash(:info, "Partner updated successfully.")
        |> redirect(to: Routes.partner_path(conn, :show, partner))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", partner: partner, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    partner = Chain.get_partner!(id)
    {:ok, _partner} = Chain.delete_partner(partner)

    conn
    |> put_flash(:info, "Partner deleted successfully.")
    |> redirect(to: Routes.partner_path(conn, :index))
  end

  def new_partner_user(conn, _opts) do
    partner = get_session(conn, :partner)
    IO.inspect(partner)

    empty_new = %{}

    if partner["type"] == "retailer" do
      empty_new = Map.put(empty_new, :role, "retailer_admin")
      IO.inspect(empty_new)
    else
      empty_new = Map.put(empty_new, :role, "supplier_admin")
      IO.inspect(empty_new)
    end

    partner_user_changeset = User.admin_changeset(%User{}, %{})
    render(conn, "new_user.html", changeset: partner_user_changeset, partner: partner)
  end

  def create_partner_user(conn, %{"user" => user_params}) do
    partner = get_session(conn, :partner)

    case Partners.create_partner_user(partner, user_params) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "User Account added successfully.")
        |> redirect(to: Routes.partner_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new_user.html", changeset: changeset)
    end

    # partner_user_changeset = User.admin_changeset(%User{}, %{})
    # render(conn, "new_user.html", changeset: partner_user_changeset)
  end

  def list_partner_products(conn, _opts) do
    products = Products.list_partner_products(conn.assigns.current_user.partner)

    IO.inspect(products)
    render(conn, "product_list.html", products: products)
  end

  def new_product(conn, _opts) do
    IO.inspect(conn.assigns.current_user.partner)
    changeset = Chain.change_product(%Product{})
    render(conn, "new_product.html", changeset: changeset)
  end

  def create_product(conn, %{"product" => product_params}) do
    case Products.create(conn.assigns.current_user.partner, product_params) do
      {:ok, _product} ->
        conn
        |> put_flash(:info, "Product created successfully.")
        |> redirect(to: Routes.partner_path(conn, :list_partner_products))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new_product.html", changeset: changeset)
    end
  end

  def show_product(conn, %{"id" => id}) do
    product = Chain.get_product!(id)
    render(conn, "show.html", product: product)
  end

  def edit_product(conn, %{"id" => id}) do
    product = Chain.get_product!(id)
    changeset = Chain.change_product(product)
    render(conn, "edit.html", product: product, changeset: changeset)
  end

  def update_product(conn, %{"id" => id, "product" => product_params}) do
    product = Chain.get_product!(id)

    case Chain.update_product(product, product_params) do
      {:ok, product} ->
        conn
        |> put_flash(:info, "Product updated successfully.")
        |> redirect(to: Routes.product_path(conn, :show, product))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", product: product, changeset: changeset)
    end
  end

  def delete_product(conn, %{"id" => id}) do
    product = Chain.get_product!(id)
    {:ok, _product} = Chain.delete_product(product)

    conn
    |> put_flash(:info, "Product deleted successfully.")
    |> redirect(to: Routes.partner_path(conn, :list_partner_products))
  end
end

kefis/lib/kefis_web/live/admin/partner/form_component.ex
defmodule KefisWeb.Admin.Partner.FormComponent do
  use KefisWeb, :live_component
  alias Kefis.Partners
  alias Kefis.Chain
  alias Kefis.Chain.Partner

  def update(%{details: %{partner: partner} = details}, socket) do
    {:ok,
     socket
     |> assign(details)
     |> assign(changeset: Chain.change_partner(partner))
     |> assign(map_component_marker_lat: -1.286389, map_component_marker_lng: 36.817223)}
  end

  def render(assigns) do
    ~H"""
    <div class="row">
    <div class="col-12 mb-4">
    <div class="card border-0 shadow">
    <div class="card-body">
    <div class="row mb-4">
    <div class="col-lg-4 col-sm-6">
      <!-- Form -->
        <div class="mb-4">

              <.form
                    let={partner_f}
                    for={@changeset}
                    phx-target={@myself}
                    phx-change="validate"
                    phx-submit="save"
                    id="admin-partner-form"
                                >
                <div class="mb-4">
                <%= label partner_f, :name, for: "name" %>
                <%= text_input partner_f, :name, class: "form-control", id: "name" %>
                <%= error_tag partner_f, :name %>
              </div>

                <div class="mb-4">
                <%= label partner_f, :location, for: "name" %>
                <%= text_input partner_f, :location, class: "form-control", id: "location" %>
                <%= error_tag partner_f, :location %>
                </div>

                <div class="mb-4">
                <%= label partner_f, :phone %>
                <%= text_input partner_f, :phone, class: "form-control", id: "phone" %>
                <%= error_tag partner_f, :phone %>
              </div>

                <div class="mb-4">
                <%= label partner_f, :email, for: "email" %>
                <%= text_input partner_f, :email, class: "form-control", id: "email" %>
                <%= error_tag partner_f, :email %>
              </div>

              <div>
              <%= submit "Save", class: "btn btn-success" %>
            </div>


              </.form>
    </div></div></div>
    </div>
    </div>
    </div>
    </div>
    """
  end

  def handle_event("validate", %{"partner" => partner_params}, socket) do
    # IO.inspect(socket)
    changeset =
      Chain.change_partner(%Partner{}, partner_params)
      |> Map.put(:action, :validate)

    {:noreply,
     socket
     |> assign(:changeset, changeset)}
  end

  def handle_event("save", %{"partner" => partner_params}, socket) do
    case Chain.update_partner(socket.assigns.partner, partner_params) do
      {:ok, partner} ->
        {:noreply,
         socket
         |> assign(:partner, partner)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply,
         socket
         |> assign(:changeset, changeset)}
    end
  end
end

kefis/lib/kefis_web/live/admin/partner/order/detail_component.ex
defmodule KefisWeb.Admin.Partner.Order.DetailComponent do
  use KefisWeb, :live_component

  def update(assigns, socket) do
    {
      :ok,
      socket
      |> assign(assigns)
    }
  end

  def render(assigns) do
    ~H"""
    <div>
    </div>
    """
  end
end

kefis/lib/kefis_web/live/admin/partner/order/list_component.ex
defmodule KefisWeb.Admin.Partner.Order.ListComponent do
  use KefisWeb, :live_component

  def update(assigns, socket) do
    {
      :ok,
      socket
      |> assign(assigns)
    }
  end

  def render(assigns) do
    ~H"""
    <div></div>
    """
  end
end

kefis/lib/kefis_web/templates/partner/dashboard_nav.html.heex
<nav class="navbar navbar-dark navbar-theme-primary px-4 col-12 d-lg-none">
    <a class="navbar-brand me-lg-5" href="../../index.html">
        <img class="navbar-brand-dark" src="" alt="Kefis" /> <img
            class="navbar-brand-light" src="" alt="Kefis" />
    </a>
    <div class="d-flex align-items-center">
        <button class="navbar-toggler d-lg-none collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>

<nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
    <div class="sidebar-inner px-4 pt-3">
        <div
            class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
            <div class="d-flex align-items-center">
                <div class="avatar-lg me-4">
                    <img src=""
                        class="card-img-top rounded-circle border-white" alt="Bonnie Green">
                </div>
                <div class="d-block">
                    <h2 class="h5 mb-3">Hi, Jane</h2>
                
                <%= link "Sign out", to: Routes.logout_path(@conn, :delete), method: :delete, class: "btn btn-secondary btn-sm d-inline-flex align-items-center" %>
                
                </div>
            </div>
            <div class="collapse-close d-md-none">
                <a href="#sidebarMenu" data-bs-toggle="collapse" data-bs-target="#sidebarMenu"
                    aria-controls="sidebarMenu" aria-expanded="true" aria-label="Toggle navigation">
                    <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                            clip-rule="evenodd"></path>
                    </svg>
                </a>
            </div>
        </div>
        <ul class="nav flex-column pt-3 pt-md-0">


            <li class="nav-item  active ">

            <%= link "Dashboard", to: Routes.partner_path(@conn, :index), class: "sidebar-text" %>
                
                
            </li>
            <li class="nav-item">


            <%= link "Products", to: Routes.partner_path(@conn, :list_partner_products), class: "sidebar-text" %>
                                
            </li>


            <li class="nav-item ">
                <a href="#" class="nav-link">
                    <span class="sidebar-icon">
                        <i class="fas fa-credit-card"></i>
                    </span>
                    <span class="sidebar-text">Transactions</span>
                </a>
            </li>


            <li class="nav-item">
                <a href="#" target="_blank"
                    class="nav-link d-flex justify-content-between">
                    <span>
                        <span class="sidebar-icon">
<i class="fa-solid fa-chart-line"></i>
                        </span>
                        <span class="sidebar-text">Analytics</span>
                    </span>
                    <span>
                        <span class="badge badge-sm bg-secondary ms-1 text-gray-800"></span>
                    </span>
                </a>
            </li>
            
            <li class="nav-item ">
                <a href="#" class="nav-link">
                    <span class="sidebar-icon">
                        <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z"
                                clip-rule="evenodd"></path>
                        </svg>
                    </span>
                    <span class="sidebar-text">Settings</span>
                </a>
            </li>

            <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>



        </ul>
    </div>
</nav>

kefis/lib/kefis_web/templates/partner/edit.html.heex
<h1>Edit Partner</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.partner_path(@conn, :update, @partner)) %>

<span><%= link "Back", to: Routes.partner_path(@conn, :index) %></span>

kefis/lib/kefis_web/templates/partner/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :location %>
  <%= text_input f, :location %>
  <%= error_tag f, :location %>

  <%= label f, :phone %>
  <%= text_input f, :phone %>
  <%= error_tag f, :phone %>

  <%= label f, :email %>
  <%= text_input f, :email %>
  <%= error_tag f, :email %>



  <%= label f, :lng %>
  <%= number_input f, :lng, step: "any" %>
  <%= error_tag f, :lng %>

  <%= label f, :lat %>
  <%= number_input f, :lat, step: "any" %>
  <%= error_tag f, :lat %>

  <%= label f, :type %>
  <%= select(f, :type, [[key: "Retailer", value: "retailer", ],
                     [key: "Supplier", value: "supplier"]]) %>
  <%= error_tag f, :type %>

  <div>
    <%= submit "Save" %>
  </div>
</.form>

kefis/lib/kefis_web/templates/partner/new.html.heex
<h1>New Partner</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.partner_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.partner_path(@conn, :index) %></span>

kefis/lib/kefis_web/templates/partner/new_product.html.heex
<%= render("dashboard_nav.html", conn: @conn) %>


<main class="content">



<%= render("dashboard_upper_nav.html", conn: @conn)  %>

<%= render("dashboard_description.html", dashboard_page_title: "New Product", dashboard_page_description: "Add a product to your catalog") %>

<%= render "product_form.html", Map.put(assigns, :action, Routes.partner_path(@conn, :new_product)) %>

</main>

kefis/lib/kefis_web/templates/partner/new_user.html.heex
<h1>Create a Partner Account for <%= @partner["name"] %></h1>

<%= render "user_form.html", Map.put(assigns, :action, Routes.partner_path(@conn, :create_partner_user)) %>


<%= form_for @changeset, Routes.partner_path(@conn, :create_partner_user), fn f -> %>
    <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :first_name %>
  <%= text_input f, :first_name %>
  <%= error_tag f, :first_name %>

  <%= label f, :second_name %>
  <%= text_input f, :second_name %>
  <%= error_tag f, :second_name %>

  <%= label f, :phone %>
  <%= text_input f, :phone %>
  <%= error_tag f, :phone %>

  <%= label f, :email %>
  <%= email_input f, :email %>
  <%= error_tag f, :email %>

    <%= label f, :password %>
  <%= password_input f, :password %>
  <%= error_tag f, :password %>

  <%= label f, :password_confirmation %>
  <%= password_input f, :password_confirmation %>
  <%= error_tag f, :password_confirmation %>


  <div>
    <%= submit "Save" %>
  </div>

<% end %>

kefis/lib/kefis_web/templates/partner/product_form.html.heex
    <div class="row">
      <div class="col-12 mb-4">
        <div class="card border-0 shadow components-section">
          <div class="card-body">
            <div class="row mb-4">
              <div class="col-lg-4 col-sm-6">
                <!-- Form -->
                <div class="mb-4">
                  
                  
                  <.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name, for: "name" %>
  <%= text_input f, :name, class: "form-control", id: "name" %>
  <%= error_tag f, :name %>

  <%= label f, :price, for: "name" %>
  <%= number_input f, :price, class: "form-control", id: "price" %>
  <%= error_tag f, :price %>

  <%= label f, :sku %>
  <%= text_input f, :sku, class: "form-control", id: "sku" %>
  <%= error_tag f, :sku %>

  <%= label f, :category, for: "category" %>
  <%= text_input f, :category, class: "form-control", id: "category" %>
  <%= error_tag f, :category %>

  <%= label f, :image, for: "image" %>
  <%= text_input f, :image, class: "form-control", id: "image" %>
  <%= error_tag f, :image %>



  <div>
    <%= submit "Save", class: "btn btn-success" %>
  </div>
</.form>
                </div>
                <!-- End of Form -->
                

              </div>
              
              
            </div>
            
          </div>
        </div>
      </div>
    </div>
    