kefis/lib/kefis_web/router.ex
defmodule KefisWeb.Router do
  use KefisWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {KefisWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug KefisWeb.ApiAuth, otp_app: :kefis
  end

  pipeline :api_protected do
    plug Pow.Plug.RequireAuthenticated, error_handler: KefisWeb.ApiAuthErrorHandler
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: KefisWeb.AuthErrorHandler
  end

  pipeline :not_authenticated do
    plug Pow.Plug.RequireNotAuthenticated,
      error_handler: KefisWeb.AuthErrorHandler
  end

  scope "/" do
    pipe_through [:browser, :not_authenticated]

    pow_routes()
  end

  scope "/", KefisWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/", KefisWeb do
    pipe_through [:browser, :protected]
    resources "/users", UserController
    resources "/products", ProductController
    # resources "/partners", PartnerController

    get "/partners/user/new", PartnerController, :new_partner_user
    post "/partners/user/new", PartnerController, :create_partner_user
    get "/partners/user/:id", PartnerController, :show_partner_user
  end

  scope "/", KefisWeb do
    pipe_through [:browser, :not_authenticated]

    # get "/signup", RegistrationController, :new, as: :signup
    # post "/signup", RegistrationController, :create, as: :signup
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
  end

  scope "/", KefisWeb do
    pipe_through [:browser, :protected]

    delete "/logout", SessionController, :delete, as: :logout
  end

  scope "/admin", KefisWeb do
    pipe_through [:browser, :protected]

    live "/", Admin.IndexLive

    live "/warehouses", Admin.Warehouse.IndexLive, :list
    live "/warehouses/new", Admin.Warehouse.IndexLive, :new
    live "/warehouses/:id", Admin.Warehouse.IndexLive, :update

    live "/transactions", Admin.Transaction.IndexLive, :transaction_index
    live "/transactions/:id", Admin.Transaction.IndexLive, :transaction_detail

    live "/partners/new", Admin.Partner.NewLive
    live "/partners/retailer", Admin.Partner.IndexLive, :retailer
    live "/partners/supplier", Admin.Partner.IndexLive, :supplier

    live "/partners/:id", Admin.Partner.IndexLive, :partner_details
    live "/partners/:id/edit", Admin.Partner.IndexLive, :edit_partner
    live "/partners/:id/orders", Admin.Partner.IndexLive, :partner_order
    live "/partners/:id/orders/:id", Admin.Partner.IndexLive, :partner_order_details

    live "/partners/:id/products/", Admin.Partner.Product.IndexLive, :partner_products
    live "/partners/:id/products/new", Admin.Partner.Product.IndexLive, :new_partner_product
    live "/partners/:id/products/:product", Admin.Partner.Product.IndexLive, :show_partner_product

    live "/partners/:id/products/:product/edit",
         Admin.Partner.Product.IndexLive,
         :edit_partner_product

    live "/partners/:id/transactions", Admin.Partner.IndexLive, :partner_transactions

    live "/orders", Admin.Order.IndexLive, :index
    live "/orders/:id", Admin.Order.IndexLive, :detail
    live "/orders/:id/info", Admin.Order.IndexLive, :info

    live "/map", Admin.Partner.IndexLive, :partner_map

    live "/users", Admin.User.IndexLive
  end

  scope "/partners", KefisWeb do
    pipe_through [:browser, :protected]

    get "/", PartnerController, :index
    get "/products", PartnerController, :list_partner_products

    get "/products/new", PartnerController, :new_product
    post "/products/new", PartnerController, :create_product

    get "/partners/products/:id", PartnerController, :show_product
    get "/partners/products/:id/edit", PartnerController, :edit_product
    delete "/partners/products/:id/delete", PartnerController, :delete_product
  end

  scope "/drivers", KefisWeb do
    pipe_through [:browser, :protected, :driver]

    live "/", Driver.DashboardLive, :index
    live "/trips", Driver.TripsLive
    live "/trips/collection", Driver.TripsLive, :collections
    live "/trips/delivery", Driver.TripsLive, :delivery

    live "/order", Driver.OrderLive
  end

  scope "/r", KefisWeb do
    pipe_through [:browser, :protected, :retailer]
    # pipe_through [:browser]

    live "/", Retailer.IndexLive

    live "/order", Retailer.OrdersLive, :index
    live "/order/new", Retailer.NewLive
    live "/order/history", Retailer.OrdersLive, :history
    live "/order/:id", Retailer.OrdersLive, :show_order

    live "/transactions", Retailer.OrdersLive, :list_my_transaction
    live "/transactions/transact", Retailer.OrdersLive, :transact
    live "/transactions/:id", Retailer.OrdersLive, :show_my_transaction

    # get "/order/new", RetailerController, :order
    live "/order/info", Retailer.ConfirmOrderLive
  end

  scope "/pos", KefisWeb do
    pipe_through [:browser, :protected, :retailer]
    # pipe_through [:browser]
  end

  scope "/s", KefisWeb do
    pipe_through [:browser, :protected, :supplier]
    # pipe_through [:browser]

    # get "/", SupplierController, :index
    # get "/products", SupplierController, :list_partner_products

    # get "/new/product", SupplierController, :new_product

    live "/", Supplier.IndexLive, :supplier_home
    live "/products", Supplier.Product.IndexLive, :list_product
    live "/products/new", Supplier.Product.IndexLive, :new_product
    live "/products/:id", Supplier.Product.IndexLive, :show_product
    live "/products/:id/edit", Supplier.Product.IndexLive, :edit_product

    live "/transactions/transact", Supplier.IndexLive, :transact_supplier
    live "/transactions", Supplier.IndexLive, :list_transactions
    live "/transactions/:id", Supplier.IndexLive, :show_transaction

    live "/orders", Supplier.IndexLive, :list_my_orders
    live "/orders/:id", Supplier.IndexLive, :show_my_orders

    # get "/orders", SupplierController, :my_orders
    # get "/orders/:id/", SupplierController, :show_order_details
  end

  scope "/w", KefisWeb do
    # pipe_through [:browser, :protected, :warehouse]
    pipe_through [:browser]

    live "/", Warehouse.IndexLive
    live "/incoming", Warehouse.OrdersLive, :incoming
    live "/processing", Warehouse.OrdersLive, :processing
    live "/outgoing", Warehouse.OrdersLive, :outgoing
    live "/info", Warehouse.ShowDetailLive
  end

  # Other scopes may use custom stacks.
  scope "/api", KefisWeb do
    pipe_through :api

    post "/login", SessionController, :api_create, as: :api_login

    # delete "/logout", SessionController, :api_delete, as: :api_logout
    post "/session/renew", SessionController, :renew
  end

  scope "/api/admin", KefisWeb do
    # pipe_through [:api, :api_protected, :api_admin]
    pipe_through :api

    get "/partners", AdminController, :api_list_partners
    post "/partners/new", AdminController, :api_add_partner
    get "/partners/:id", AdminController, :api_admin_show_partner
    post "/partners/:id/edit", AdminController, :api_update_partner
    delete "/partners/:id", AdminController, :api_delete_partner
    get "/partners/:id/products", AdminController, :api_show_partner_w_products

    get "/partners/:id/products/:id", AdminController, :api_show_partner_w_products
    post "/partners/:id/products/new", AdminController, :api_add_product
    post "/partners/:id/products/:product_id/edit", AdminController, :api_update_product
    delete "/partners/:id/products/:product_id/delete", AdminController, :api_delete_product

    get "/orders", AdminController, :api_list_orders
    get "/orders/:id", AdminController, :api_show_order
  end

  scope "/api/s", KefisWeb do
    pipe_through [:api, :api_supplier]

    get "/partners", AdminController, :api_list_partners
    get "/partners/:id", AdminController, :api_show_partner
  end

  scope "/api/r", KefisWeb do
    pipe_through [:api, :api_retailer]

    get "/partners", AdminController, :api_list_partners
    get "/partners/:id", AdminController, :api_show_partner
  end

  scope "/api", KefisWeb do
    pipe_through [:api, :api_protected]
    delete "/logout", SessionController, :delete, as: :logout
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: KefisWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

kefis/lib/kefis_web/controllers/session_controller.ex
defmodule KefisWeb.SessionController do
  use KefisWeb, :controller
  alias Kefis.Repo
  alias Kefis.Users.User
  alias KefisWeb.Auth

  alias KefisWeb.ApiAuth

  def new(conn, _params) do
    changeset = Pow.Plug.change_user(conn)

    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    conn
    |> Pow.Plug.authenticate_user(user_params)
    |> case do
      {:ok, conn} ->
        config = Pow.Plug.fetch_config(conn)
        user = Pow.Plug.current_user(conn, config)
        reloaded_user = Repo.get!(User, user.id) |> Repo.preload([:driver, :partner, :warehouse])
        Pow.Plug.assign_current_user(conn, reloaded_user, config)

        conn
        |> Pow.Plug.assign_current_user(reloaded_user, config)
        |> put_session(:user, reloaded_user)
        |> put_flash(:info, "Welcome back!")
        |> Auth.landing_page(reloaded_user)

      {:error, conn} ->
        changeset = Pow.Plug.change_user(conn, conn.params["user"])

        conn
        |> put_flash(:error, "Invalid email or password")
        |> render("new.html", changeset: changeset)
    end
  end

  def delete(conn, _params) do
    conn
    |> Pow.Plug.delete()
    |> configure_session(renew: true)
    |> clear_session()
    |> redirect(to: Routes.page_path(conn, :index))
  end

  ### API ###
  def api_create(conn, %{"user" => user_params}) do
    IO.inspect(user_params)

    conn
    |> Pow.Plug.authenticate_user(user_params)
    |> case do
      {:ok, conn} ->
        config = Pow.Plug.fetch_config(conn)
        user = Pow.Plug.current_user(conn, config)

        json(conn, %{
          access_token: conn.private.api_access_token,
          renewal_token: conn.private.api_renewal_token,
          first_name: user.first_name,
          email: user.email,
          second_name: user.second_name,
          role: user.role,
          phone: user.phone
        })

      {:error, conn} ->
        conn
        |> put_status(401)
        |> json(%{error: %{status: 401, message: "Invalid Credentials"}})
    end
  end

  def api_renew(conn, _params) do
    config = Pow.Plug.fetch_config(conn)

    conn
    |> ApiAuth.renew(config)
    |> case do
      {conn, nil} ->
        conn
        |> put_status(401)
        |> json(%{error: %{status: 401, message: "Invalid token"}})

      {conn, _user} ->
        json(conn, %{
          data: %{
            access_token: conn.private.api_access_token,
            renewal_token: conn.private.api_renewal_token
          }
        })
    end
  end

  def api_delete(conn, _params) do
    conn
    |> Pow.Plug.delete()
    |> json(%{data: %{}})
  end
end

kefis/lib/kefis_web/views/session_view.ex
defmodule KefisWeb.SessionView do
  use KefisWeb, :view
end

kefis/lib/kefis_web/templates/session/new.html.eex
    <main>

        <!-- Section -->
        <section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
            <div class="container">
                <p class="text-center">

                    <%= link("Back to homepage", to: "/", class: "d-flex align-items-center justify-content-center") %>
                    
                    
                </p>
                <div class="row justify-content-center form-bg-image" data-background-lg={Routes.static_path(@conn, "/images/h.jpg")}>
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="bg-white shadow border-0 rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">Sign in to our platform</h1>
                            </div>
                                            <%= form_for @changeset, Routes.login_path(@conn, :create), fn f -> %>
                            <form action="#" class="mt-4">
                                <!-- Form -->
                                <div class="form-group mb-4">
                                
                                      <%= label  f, :email, for: "email"   %>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1">
                                            <svg class="icon icon-xs text-gray-600" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z"></path><path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z"></path></svg>
                                        </span>
  <%= email_input f, :email, class: "form-control", id: "email", autofocus: true, required: true, placeholder: "example@company.com" %>
                                    </div>  
                                </div>
                                <!-- End of Form -->
                                <div class="form-group">
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                    
                                            <%= label f, :password,  for: "password" %>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon2">
                                                <svg class="icon icon-xs text-gray-600" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd"></path></svg>
                                            </span>
                                            <%= password_input f, :password, class: "form-control", id: "password", required: true, placeholder: "password" %>
                                  
                                        </div>  
                                    </div>
                                    <!-- End of Form -->
                                    
                                </div>
                                <div class="d-grid">
                                
                                      <%= submit "Sign in", class: "btn btn-gray-800" %>
                                </div>

                            </form>
                            <% end %>
                            
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>